#ifndef WEBSERVER_STATUS_H
#define WEBSERVER_STATUS_H

#include <stddef.h>
#include <stdint.h>

#define STATUS_CONTINUE 100
#define STATUS_SWITCHING_PROTOCOLS 101
#define STATUS_PROCESSING 102
#define STATUS_EARLY_HINTS 103

#define STATUS_OK 200
#define STATUS_CREATED 201
#define STATUS_ACCEPTED 202
#define STATUS_NON_AUTHORITATIVE_INFORMATION 203
#define STATUS_NO_CONTENT 204
#define STATUS_RESET_CONTENT 205
#define STATUS_PARTIAL_CONTENT 206
#define STATUS_MULTI_STATUS 207
#define STATUS_ALREADY_REPORTED 208
#define STATUS_IM_USED 226

#define STATUS_MULTIPLE_CHOICES 300
#define STATUS_MOVED_PERMANENTLY 301
#define STATUS_FOUND 302
#define STATUS_SEE_OTHER 303
#define STATUS_NOT_MODIFIED 304
#define STATUS_USE_PROXY 305
#define STATUS_UNUSED 306
#define STATUS_TEMPORARY_REDIRECT 307
#define STATUS_PERMANENT_REDIRECT 308

#define STATUS_BAD_REQUEST 400
#define STATUS_UNAUTHORIZED 401
#define STATUS_PAYMENT_REQUIRED 402
#define STATUS_FORBIDDEN 403
#define STATUS_NOT_FOUND 404
#define STATUS_NOT_ALLOWED 405
#define STATUS_NOT_ACCEPTABLE 406
#define STATUS_PROXY_AUTHENTICATION_REQUIRED 407
#define STATUS_REQUEST_TIMEOUT 408
#define STATUS_CONFLICT 409
#define STATUS_GONE 410
#define STATUS_LENGTH_REQUIRED 411
#define STATUS_PRECONDITION_FAILED 412
#define STATUS_CONTENT_TOO_LARGE 413
#define STATUS_URI_TOO_LONG 414
#define STATUS_UNSUPPORTED_MEDIA_TYPE 415
#define STATUS_RANGE_NOT_SATISFIABLE 416
#define STATUS_EXPECTATION_FAILED 417
#define STATUS_IM_A_TEAPOT 418
#define STATUS_MISDIRECTED_REQUEST 421
#define STATUS_UNPROCESSABLE_ENTITY 422
#define STATUS_LOCKED 423
#define STATUS_FAILED_DEPENDENCY 424
#define STATUS_TOO_EARLY 425
#define STATUS_UPGRADE_REQUIRED 426
#define STATUS_PRECONDITION_REQUIRED 428
#define STATUS_TOO_MANY_REQUESTS 429
#define STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define STATUS_UNAVAILABLE_FOR_LEGAL_REASONS 451

#define STATUS_INTERNAL_SERVER_ERROR 500
#define STATUS_NOT_IMPLEMENTED 501
#define STATUS_BAD_GATEWAY 502
#define STATUS_SERVICE_UNAVAILABLE 503
#define STATUS_GATEWAY_TIMEOUT 504
#define STATUS_HTTP_VERSION_NOT_SUPPORTED 505
#define STATUS_VARIANT_ALSO_NEGOTIATES 506
#define STATUS_INSUFFICIENT_STORAGE 507
#define STATUS_LOOP_DETECTED 508
#define STATUS_NOT_EXTENDED 510
#define STATUS_NETWORK_AUTHENTICATION_REQUIRED 511

#endif
